version: "3"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"

  test:
    build:
      context: .
      dockerfile: ci.dockerfile
    environment:
      MINIO_HOST: http://minio:9000
    links:
      - minio
    command: go test ./... -v
